/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource } from './IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource.ts';
import { IoK8sApiCoreV1AzureDiskVolumeSource } from './IoK8sApiCoreV1AzureDiskVolumeSource.ts';
import { IoK8sApiCoreV1AzureFileVolumeSource } from './IoK8sApiCoreV1AzureFileVolumeSource.ts';
import { IoK8sApiCoreV1CSIVolumeSource } from './IoK8sApiCoreV1CSIVolumeSource.ts';
import { IoK8sApiCoreV1CephFSVolumeSource } from './IoK8sApiCoreV1CephFSVolumeSource.ts';
import { IoK8sApiCoreV1CinderVolumeSource } from './IoK8sApiCoreV1CinderVolumeSource.ts';
import { IoK8sApiCoreV1ConfigMapVolumeSource } from './IoK8sApiCoreV1ConfigMapVolumeSource.ts';
import { IoK8sApiCoreV1DownwardAPIVolumeSource } from './IoK8sApiCoreV1DownwardAPIVolumeSource.ts';
import { IoK8sApiCoreV1EmptyDirVolumeSource } from './IoK8sApiCoreV1EmptyDirVolumeSource.ts';
import { IoK8sApiCoreV1EphemeralVolumeSource } from './IoK8sApiCoreV1EphemeralVolumeSource.ts';
import { IoK8sApiCoreV1FCVolumeSource } from './IoK8sApiCoreV1FCVolumeSource.ts';
import { IoK8sApiCoreV1FlexVolumeSource } from './IoK8sApiCoreV1FlexVolumeSource.ts';
import { IoK8sApiCoreV1FlockerVolumeSource } from './IoK8sApiCoreV1FlockerVolumeSource.ts';
import { IoK8sApiCoreV1GCEPersistentDiskVolumeSource } from './IoK8sApiCoreV1GCEPersistentDiskVolumeSource.ts';
import { IoK8sApiCoreV1GitRepoVolumeSource } from './IoK8sApiCoreV1GitRepoVolumeSource.ts';
import { IoK8sApiCoreV1GlusterfsVolumeSource } from './IoK8sApiCoreV1GlusterfsVolumeSource.ts';
import { IoK8sApiCoreV1HostPathVolumeSource } from './IoK8sApiCoreV1HostPathVolumeSource.ts';
import { IoK8sApiCoreV1ISCSIVolumeSource } from './IoK8sApiCoreV1ISCSIVolumeSource.ts';
import { IoK8sApiCoreV1NFSVolumeSource } from './IoK8sApiCoreV1NFSVolumeSource.ts';
import { IoK8sApiCoreV1PersistentVolumeClaimVolumeSource } from './IoK8sApiCoreV1PersistentVolumeClaimVolumeSource.ts';
import { IoK8sApiCoreV1PhotonPersistentDiskVolumeSource } from './IoK8sApiCoreV1PhotonPersistentDiskVolumeSource.ts';
import { IoK8sApiCoreV1PortworxVolumeSource } from './IoK8sApiCoreV1PortworxVolumeSource.ts';
import { IoK8sApiCoreV1ProjectedVolumeSource } from './IoK8sApiCoreV1ProjectedVolumeSource.ts';
import { IoK8sApiCoreV1QuobyteVolumeSource } from './IoK8sApiCoreV1QuobyteVolumeSource.ts';
import { IoK8sApiCoreV1RBDVolumeSource } from './IoK8sApiCoreV1RBDVolumeSource.ts';
import { IoK8sApiCoreV1ScaleIOVolumeSource } from './IoK8sApiCoreV1ScaleIOVolumeSource.ts';
import { IoK8sApiCoreV1SecretVolumeSource } from './IoK8sApiCoreV1SecretVolumeSource.ts';
import { IoK8sApiCoreV1StorageOSVolumeSource } from './IoK8sApiCoreV1StorageOSVolumeSource.ts';
import { IoK8sApiCoreV1VsphereVirtualDiskVolumeSource } from './IoK8sApiCoreV1VsphereVirtualDiskVolumeSource.ts';
import { HttpFile } from '../http/http.ts';

/**
* Volume represents a named volume in a pod that may be accessed by any container in the pod.
*/
export class IoK8sApiCoreV1Volume {
    'awsElasticBlockStore'?: IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource;
    'azureDisk'?: IoK8sApiCoreV1AzureDiskVolumeSource;
    'azureFile'?: IoK8sApiCoreV1AzureFileVolumeSource;
    'cephfs'?: IoK8sApiCoreV1CephFSVolumeSource;
    'cinder'?: IoK8sApiCoreV1CinderVolumeSource;
    'configMap'?: IoK8sApiCoreV1ConfigMapVolumeSource;
    'csi'?: IoK8sApiCoreV1CSIVolumeSource;
    'downwardAPI'?: IoK8sApiCoreV1DownwardAPIVolumeSource;
    'emptyDir'?: IoK8sApiCoreV1EmptyDirVolumeSource;
    'ephemeral'?: IoK8sApiCoreV1EphemeralVolumeSource;
    'fc'?: IoK8sApiCoreV1FCVolumeSource;
    'flexVolume'?: IoK8sApiCoreV1FlexVolumeSource;
    'flocker'?: IoK8sApiCoreV1FlockerVolumeSource;
    'gcePersistentDisk'?: IoK8sApiCoreV1GCEPersistentDiskVolumeSource;
    'gitRepo'?: IoK8sApiCoreV1GitRepoVolumeSource;
    'glusterfs'?: IoK8sApiCoreV1GlusterfsVolumeSource;
    'hostPath'?: IoK8sApiCoreV1HostPathVolumeSource;
    'iscsi'?: IoK8sApiCoreV1ISCSIVolumeSource;
    /**
    * name of the volume. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    */
    'name': string;
    'nfs'?: IoK8sApiCoreV1NFSVolumeSource;
    'persistentVolumeClaim'?: IoK8sApiCoreV1PersistentVolumeClaimVolumeSource;
    'photonPersistentDisk'?: IoK8sApiCoreV1PhotonPersistentDiskVolumeSource;
    'portworxVolume'?: IoK8sApiCoreV1PortworxVolumeSource;
    'projected'?: IoK8sApiCoreV1ProjectedVolumeSource;
    'quobyte'?: IoK8sApiCoreV1QuobyteVolumeSource;
    'rbd'?: IoK8sApiCoreV1RBDVolumeSource;
    'scaleIO'?: IoK8sApiCoreV1ScaleIOVolumeSource;
    'secret'?: IoK8sApiCoreV1SecretVolumeSource;
    'storageos'?: IoK8sApiCoreV1StorageOSVolumeSource;
    'vsphereVolume'?: IoK8sApiCoreV1VsphereVirtualDiskVolumeSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "awsElasticBlockStore",
            "baseName": "awsElasticBlockStore",
            "type": "IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource",
            "format": ""
        },
        {
            "name": "azureDisk",
            "baseName": "azureDisk",
            "type": "IoK8sApiCoreV1AzureDiskVolumeSource",
            "format": ""
        },
        {
            "name": "azureFile",
            "baseName": "azureFile",
            "type": "IoK8sApiCoreV1AzureFileVolumeSource",
            "format": ""
        },
        {
            "name": "cephfs",
            "baseName": "cephfs",
            "type": "IoK8sApiCoreV1CephFSVolumeSource",
            "format": ""
        },
        {
            "name": "cinder",
            "baseName": "cinder",
            "type": "IoK8sApiCoreV1CinderVolumeSource",
            "format": ""
        },
        {
            "name": "configMap",
            "baseName": "configMap",
            "type": "IoK8sApiCoreV1ConfigMapVolumeSource",
            "format": ""
        },
        {
            "name": "csi",
            "baseName": "csi",
            "type": "IoK8sApiCoreV1CSIVolumeSource",
            "format": ""
        },
        {
            "name": "downwardAPI",
            "baseName": "downwardAPI",
            "type": "IoK8sApiCoreV1DownwardAPIVolumeSource",
            "format": ""
        },
        {
            "name": "emptyDir",
            "baseName": "emptyDir",
            "type": "IoK8sApiCoreV1EmptyDirVolumeSource",
            "format": ""
        },
        {
            "name": "ephemeral",
            "baseName": "ephemeral",
            "type": "IoK8sApiCoreV1EphemeralVolumeSource",
            "format": ""
        },
        {
            "name": "fc",
            "baseName": "fc",
            "type": "IoK8sApiCoreV1FCVolumeSource",
            "format": ""
        },
        {
            "name": "flexVolume",
            "baseName": "flexVolume",
            "type": "IoK8sApiCoreV1FlexVolumeSource",
            "format": ""
        },
        {
            "name": "flocker",
            "baseName": "flocker",
            "type": "IoK8sApiCoreV1FlockerVolumeSource",
            "format": ""
        },
        {
            "name": "gcePersistentDisk",
            "baseName": "gcePersistentDisk",
            "type": "IoK8sApiCoreV1GCEPersistentDiskVolumeSource",
            "format": ""
        },
        {
            "name": "gitRepo",
            "baseName": "gitRepo",
            "type": "IoK8sApiCoreV1GitRepoVolumeSource",
            "format": ""
        },
        {
            "name": "glusterfs",
            "baseName": "glusterfs",
            "type": "IoK8sApiCoreV1GlusterfsVolumeSource",
            "format": ""
        },
        {
            "name": "hostPath",
            "baseName": "hostPath",
            "type": "IoK8sApiCoreV1HostPathVolumeSource",
            "format": ""
        },
        {
            "name": "iscsi",
            "baseName": "iscsi",
            "type": "IoK8sApiCoreV1ISCSIVolumeSource",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nfs",
            "baseName": "nfs",
            "type": "IoK8sApiCoreV1NFSVolumeSource",
            "format": ""
        },
        {
            "name": "persistentVolumeClaim",
            "baseName": "persistentVolumeClaim",
            "type": "IoK8sApiCoreV1PersistentVolumeClaimVolumeSource",
            "format": ""
        },
        {
            "name": "photonPersistentDisk",
            "baseName": "photonPersistentDisk",
            "type": "IoK8sApiCoreV1PhotonPersistentDiskVolumeSource",
            "format": ""
        },
        {
            "name": "portworxVolume",
            "baseName": "portworxVolume",
            "type": "IoK8sApiCoreV1PortworxVolumeSource",
            "format": ""
        },
        {
            "name": "projected",
            "baseName": "projected",
            "type": "IoK8sApiCoreV1ProjectedVolumeSource",
            "format": ""
        },
        {
            "name": "quobyte",
            "baseName": "quobyte",
            "type": "IoK8sApiCoreV1QuobyteVolumeSource",
            "format": ""
        },
        {
            "name": "rbd",
            "baseName": "rbd",
            "type": "IoK8sApiCoreV1RBDVolumeSource",
            "format": ""
        },
        {
            "name": "scaleIO",
            "baseName": "scaleIO",
            "type": "IoK8sApiCoreV1ScaleIOVolumeSource",
            "format": ""
        },
        {
            "name": "secret",
            "baseName": "secret",
            "type": "IoK8sApiCoreV1SecretVolumeSource",
            "format": ""
        },
        {
            "name": "storageos",
            "baseName": "storageos",
            "type": "IoK8sApiCoreV1StorageOSVolumeSource",
            "format": ""
        },
        {
            "name": "vsphereVolume",
            "baseName": "vsphereVolume",
            "type": "IoK8sApiCoreV1VsphereVirtualDiskVolumeSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1Volume.attributeTypeMap;
    }

    public constructor() {
    }
}

