/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAppsV1RollingUpdateDeployment } from './IoK8sApiAppsV1RollingUpdateDeployment.ts';
import { HttpFile } from '../http/http.ts';

/**
* DeploymentStrategy describes how to replace existing pods with new ones.
*/
export class IoK8sApiAppsV1DeploymentStrategy {
    'rollingUpdate'?: IoK8sApiAppsV1RollingUpdateDeployment;
    /**
    * Type of deployment. Can be \"Recreate\" or \"RollingUpdate\". Default is RollingUpdate.  Possible enum values:  - `\"Recreate\"` Kill all existing pods before creating new ones.  - `\"RollingUpdate\"` Replace the old ReplicaSets by new one using rolling update i.e gradually scale down the old ReplicaSets and scale up the new one.
    */
    'type'?: IoK8sApiAppsV1DeploymentStrategyTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rollingUpdate",
            "baseName": "rollingUpdate",
            "type": "IoK8sApiAppsV1RollingUpdateDeployment",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IoK8sApiAppsV1DeploymentStrategyTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAppsV1DeploymentStrategy.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IoK8sApiAppsV1DeploymentStrategyTypeEnum = "Recreate" | "RollingUpdate" ;

