/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* Adds and removes POSIX capabilities from running containers.
*/
export class IoK8sApiCoreV1Capabilities {
    /**
    * Added capabilities
    */
    'add'?: Array<string>;
    /**
    * Removed capabilities
    */
    'drop'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "add",
            "baseName": "add",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "drop",
            "baseName": "drop",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1Capabilities.attributeTypeMap;
    }

    public constructor() {
    }
}

