/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition } from './IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition.ts';
import { IoK8sApiAutoscalingV2beta2MetricStatus } from './IoK8sApiAutoscalingV2beta2MetricStatus.ts';
import { HttpFile } from '../http/http.ts';

/**
* HorizontalPodAutoscalerStatus describes the current status of a horizontal pod autoscaler.
*/
export class IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus {
    /**
    * conditions is the set of conditions required for this autoscaler to scale its target, and indicates whether or not those conditions are met.
    */
    'conditions'?: Array<IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition>;
    /**
    * currentMetrics is the last read state of the metrics used by this autoscaler.
    */
    'currentMetrics'?: Array<IoK8sApiAutoscalingV2beta2MetricStatus>;
    /**
    * currentReplicas is current number of replicas of pods managed by this autoscaler, as last seen by the autoscaler.
    */
    'currentReplicas': number;
    /**
    * desiredReplicas is the desired number of replicas of pods managed by this autoscaler, as last calculated by the autoscaler.
    */
    'desiredReplicas': number;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'lastScaleTime'?: Date;
    /**
    * observedGeneration is the most recent generation observed by this autoscaler.
    */
    'observedGeneration'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerCondition>",
            "format": ""
        },
        {
            "name": "currentMetrics",
            "baseName": "currentMetrics",
            "type": "Array<IoK8sApiAutoscalingV2beta2MetricStatus>",
            "format": ""
        },
        {
            "name": "currentReplicas",
            "baseName": "currentReplicas",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "desiredReplicas",
            "baseName": "desiredReplicas",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "lastScaleTime",
            "baseName": "lastScaleTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "observedGeneration",
            "baseName": "observedGeneration",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAutoscalingV2beta2HorizontalPodAutoscalerStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

