/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiPolicyV1beta1IDRange } from './IoK8sApiPolicyV1beta1IDRange.ts';
import { HttpFile } from '../http/http.ts';

/**
* SupplementalGroupsStrategyOptions defines the strategy type and options used to create the strategy.
*/
export class IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions {
    /**
    * ranges are the allowed ranges of supplemental groups.  If you would like to force a single supplemental group then supply a single range with the same start and end. Required for MustRunAs.
    */
    'ranges'?: Array<IoK8sApiPolicyV1beta1IDRange>;
    /**
    * rule is the strategy that will dictate what supplemental groups is used in the SecurityContext.
    */
    'rule'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ranges",
            "baseName": "ranges",
            "type": "Array<IoK8sApiPolicyV1beta1IDRange>",
            "format": ""
        },
        {
            "name": "rule",
            "baseName": "rule",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiPolicyV1beta1SupplementalGroupsStrategyOptions.attributeTypeMap;
    }

    public constructor() {
    }
}

