/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationCondition } from './IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationCondition.ts';
import { HttpFile } from '../http/http.ts';

/**
* PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".
*/
export class IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationStatus {
    /**
    * `conditions` is the current state of \"request-priority\".
    */
    'conditions'?: Array<IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationCondition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationCondition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

