/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAppsV1StatefulSetPersistentVolumeClaimRetentionPolicy } from './IoK8sApiAppsV1StatefulSetPersistentVolumeClaimRetentionPolicy.ts';
import { IoK8sApiAppsV1StatefulSetUpdateStrategy } from './IoK8sApiAppsV1StatefulSetUpdateStrategy.ts';
import { IoK8sApiCoreV1PersistentVolumeClaim } from './IoK8sApiCoreV1PersistentVolumeClaim.ts';
import { IoK8sApiCoreV1PodTemplateSpec } from './IoK8sApiCoreV1PodTemplateSpec.ts';
import { IoK8sApimachineryPkgApisMetaV1LabelSelector } from './IoK8sApimachineryPkgApisMetaV1LabelSelector.ts';
import { HttpFile } from '../http/http.ts';

/**
* A StatefulSetSpec is the specification of a StatefulSet.
*/
export class IoK8sApiAppsV1StatefulSetSpec {
    /**
    * Minimum number of seconds for which a newly created pod should be ready without any of its container crashing for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready) This is an alpha field and requires enabling StatefulSetMinReadySeconds feature gate.
    */
    'minReadySeconds'?: number;
    'persistentVolumeClaimRetentionPolicy'?: IoK8sApiAppsV1StatefulSetPersistentVolumeClaimRetentionPolicy;
    /**
    * podManagementPolicy controls how pods are created during initial scale up, when replacing pods on nodes, or when scaling down. The default policy is `OrderedReady`, where pods are created in increasing order (pod-0, then pod-1, etc) and the controller will wait until each pod is ready before continuing. When scaling down, the pods are removed in the opposite order. The alternative policy is `Parallel` which will create pods in parallel to match the desired scale without waiting, and on scale down will delete all pods at once.  Possible enum values:  - `\"OrderedReady\"` will create pods in strictly increasing order on scale up and strictly decreasing order on scale down, progressing only when the previous pod is ready or terminated. At most one pod will be changed at any time.  - `\"Parallel\"` will create and delete pods as soon as the stateful set replica count is changed, and will not wait for pods to be ready or complete termination.
    */
    'podManagementPolicy'?: IoK8sApiAppsV1StatefulSetSpecPodManagementPolicyEnum;
    /**
    * replicas is the desired number of replicas of the given Template. These are replicas in the sense that they are instantiations of the same Template, but individual replicas also have a consistent identity. If unspecified, defaults to 1.
    */
    'replicas'?: number;
    /**
    * revisionHistoryLimit is the maximum number of revisions that will be maintained in the StatefulSet's revision history. The revision history consists of all revisions not represented by a currently applied StatefulSetSpec version. The default value is 10.
    */
    'revisionHistoryLimit'?: number;
    'selector': IoK8sApimachineryPkgApisMetaV1LabelSelector;
    /**
    * serviceName is the name of the service that governs this StatefulSet. This service must exist before the StatefulSet, and is responsible for the network identity of the set. Pods get DNS/hostnames that follow the pattern: pod-specific-string.serviceName.default.svc.cluster.local where \"pod-specific-string\" is managed by the StatefulSet controller.
    */
    'serviceName': string;
    'template': IoK8sApiCoreV1PodTemplateSpec;
    'updateStrategy'?: IoK8sApiAppsV1StatefulSetUpdateStrategy;
    /**
    * volumeClaimTemplates is a list of claims that pods are allowed to reference. The StatefulSet controller is responsible for mapping network identities to claims in a way that maintains the identity of a pod. Every claim in this list must have at least one matching (by name) volumeMount in one container in the template. A claim in this list takes precedence over any volumes in the template, with the same name.
    */
    'volumeClaimTemplates'?: Array<IoK8sApiCoreV1PersistentVolumeClaim>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "minReadySeconds",
            "baseName": "minReadySeconds",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "persistentVolumeClaimRetentionPolicy",
            "baseName": "persistentVolumeClaimRetentionPolicy",
            "type": "IoK8sApiAppsV1StatefulSetPersistentVolumeClaimRetentionPolicy",
            "format": ""
        },
        {
            "name": "podManagementPolicy",
            "baseName": "podManagementPolicy",
            "type": "IoK8sApiAppsV1StatefulSetSpecPodManagementPolicyEnum",
            "format": ""
        },
        {
            "name": "replicas",
            "baseName": "replicas",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "revisionHistoryLimit",
            "baseName": "revisionHistoryLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "selector",
            "baseName": "selector",
            "type": "IoK8sApimachineryPkgApisMetaV1LabelSelector",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "serviceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "IoK8sApiCoreV1PodTemplateSpec",
            "format": ""
        },
        {
            "name": "updateStrategy",
            "baseName": "updateStrategy",
            "type": "IoK8sApiAppsV1StatefulSetUpdateStrategy",
            "format": ""
        },
        {
            "name": "volumeClaimTemplates",
            "baseName": "volumeClaimTemplates",
            "type": "Array<IoK8sApiCoreV1PersistentVolumeClaim>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAppsV1StatefulSetSpec.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IoK8sApiAppsV1StatefulSetSpecPodManagementPolicyEnum = "OrderedReady" | "Parallel" ;

