/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1ConfigMapEnvSource } from './IoK8sApiCoreV1ConfigMapEnvSource.ts';
import { IoK8sApiCoreV1SecretEnvSource } from './IoK8sApiCoreV1SecretEnvSource.ts';
import { HttpFile } from '../http/http.ts';

/**
* EnvFromSource represents the source of a set of ConfigMaps
*/
export class IoK8sApiCoreV1EnvFromSource {
    'configMapRef'?: IoK8sApiCoreV1ConfigMapEnvSource;
    /**
    * An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
    */
    'prefix'?: string;
    'secretRef'?: IoK8sApiCoreV1SecretEnvSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "configMapRef",
            "baseName": "configMapRef",
            "type": "IoK8sApiCoreV1ConfigMapEnvSource",
            "format": ""
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "secretRef",
            "baseName": "secretRef",
            "type": "IoK8sApiCoreV1SecretEnvSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1EnvFromSource.attributeTypeMap;
    }

    public constructor() {
    }
}

