/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAuthenticationV1BoundObjectReference } from './IoK8sApiAuthenticationV1BoundObjectReference.ts';
import { HttpFile } from '../http/http.ts';

/**
* TokenRequestSpec contains client provided parameters of a token request.
*/
export class IoK8sApiAuthenticationV1TokenRequestSpec {
    /**
    * Audiences are the intendend audiences of the token. A recipient of a token must identitfy themself with an identifier in the list of audiences of the token, and otherwise should reject the token. A token issued for multiple audiences may be used to authenticate against any of the audiences listed but implies a high degree of trust between the target audiences.
    */
    'audiences': Array<string>;
    'boundObjectRef'?: IoK8sApiAuthenticationV1BoundObjectReference;
    /**
    * ExpirationSeconds is the requested duration of validity of the request. The token issuer may return a token with a different validity duration so a client needs to check the 'expiration' field in a response.
    */
    'expirationSeconds'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "audiences",
            "baseName": "audiences",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "boundObjectRef",
            "baseName": "boundObjectRef",
            "type": "IoK8sApiAuthenticationV1BoundObjectReference",
            "format": ""
        },
        {
            "name": "expirationSeconds",
            "baseName": "expirationSeconds",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAuthenticationV1TokenRequestSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

