/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAutoscalingV2beta1CrossVersionObjectReference } from './IoK8sApiAutoscalingV2beta1CrossVersionObjectReference.ts';
import { IoK8sApiAutoscalingV2beta1MetricSpec } from './IoK8sApiAutoscalingV2beta1MetricSpec.ts';
import { HttpFile } from '../http/http.ts';

/**
* HorizontalPodAutoscalerSpec describes the desired functionality of the HorizontalPodAutoscaler.
*/
export class IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerSpec {
    /**
    * maxReplicas is the upper limit for the number of replicas to which the autoscaler can scale up. It cannot be less that minReplicas.
    */
    'maxReplicas': number;
    /**
    * metrics contains the specifications for which to use to calculate the desired replica count (the maximum replica count across all metrics will be used).  The desired replica count is calculated multiplying the ratio between the target value and the current value by the current number of pods.  Ergo, metrics used must decrease as the pod count is increased, and vice-versa.  See the individual metric source types for more information about how each type of metric must respond.
    */
    'metrics'?: Array<IoK8sApiAutoscalingV2beta1MetricSpec>;
    /**
    * minReplicas is the lower limit for the number of replicas to which the autoscaler can scale down.  It defaults to 1 pod.  minReplicas is allowed to be 0 if the alpha feature gate HPAScaleToZero is enabled and at least one Object or External metric is configured.  Scaling is active as long as at least one metric value is available.
    */
    'minReplicas'?: number;
    'scaleTargetRef': IoK8sApiAutoscalingV2beta1CrossVersionObjectReference;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxReplicas",
            "baseName": "maxReplicas",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "Array<IoK8sApiAutoscalingV2beta1MetricSpec>",
            "format": ""
        },
        {
            "name": "minReplicas",
            "baseName": "minReplicas",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "scaleTargetRef",
            "baseName": "scaleTargetRef",
            "type": "IoK8sApiAutoscalingV2beta1CrossVersionObjectReference",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

