/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1ExecAction } from './IoK8sApiCoreV1ExecAction.ts';
import { IoK8sApiCoreV1HTTPGetAction } from './IoK8sApiCoreV1HTTPGetAction.ts';
import { IoK8sApiCoreV1TCPSocketAction } from './IoK8sApiCoreV1TCPSocketAction.ts';
import { HttpFile } from '../http/http.ts';

/**
* LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
*/
export class IoK8sApiCoreV1LifecycleHandler {
    'exec'?: IoK8sApiCoreV1ExecAction;
    'httpGet'?: IoK8sApiCoreV1HTTPGetAction;
    'tcpSocket'?: IoK8sApiCoreV1TCPSocketAction;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "exec",
            "baseName": "exec",
            "type": "IoK8sApiCoreV1ExecAction",
            "format": ""
        },
        {
            "name": "httpGet",
            "baseName": "httpGet",
            "type": "IoK8sApiCoreV1HTTPGetAction",
            "format": ""
        },
        {
            "name": "tcpSocket",
            "baseName": "tcpSocket",
            "type": "IoK8sApiCoreV1TCPSocketAction",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1LifecycleHandler.attributeTypeMap;
    }

    public constructor() {
    }
}

