/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAppsV1RollingUpdateStatefulSetStrategy } from './IoK8sApiAppsV1RollingUpdateStatefulSetStrategy.ts';
import { HttpFile } from '../http/http.ts';

/**
* StatefulSetUpdateStrategy indicates the strategy that the StatefulSet controller will use to perform updates. It includes any additional parameters necessary to perform the update for the indicated strategy.
*/
export class IoK8sApiAppsV1StatefulSetUpdateStrategy {
    'rollingUpdate'?: IoK8sApiAppsV1RollingUpdateStatefulSetStrategy;
    /**
    * Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.  Possible enum values:  - `\"OnDelete\"` triggers the legacy behavior. Version tracking and ordered rolling restarts are disabled. Pods are recreated from the StatefulSetSpec when they are manually deleted. When a scale operation is performed with this strategy,specification version indicated by the StatefulSet's currentRevision.  - `\"RollingUpdate\"` indicates that update will be applied to all Pods in the StatefulSet with respect to the StatefulSet ordering constraints. When a scale operation is performed with this strategy, new Pods will be created from the specification version indicated by the StatefulSet's updateRevision.
    */
    'type'?: IoK8sApiAppsV1StatefulSetUpdateStrategyTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rollingUpdate",
            "baseName": "rollingUpdate",
            "type": "IoK8sApiAppsV1RollingUpdateStatefulSetStrategy",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IoK8sApiAppsV1StatefulSetUpdateStrategyTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAppsV1StatefulSetUpdateStrategy.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IoK8sApiAppsV1StatefulSetUpdateStrategyTypeEnum = "OnDelete" | "RollingUpdate" ;

