/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApimachineryPkgApisMetaV1Condition } from './IoK8sApimachineryPkgApisMetaV1Condition.ts';
import { HttpFile } from '../http/http.ts';

/**
* NetworkPolicyStatus describe the current state of the NetworkPolicy.
*/
export class IoK8sApiNetworkingV1NetworkPolicyStatus {
    /**
    * Conditions holds an array of metav1.Condition that describe the state of the NetworkPolicy. Current service state
    */
    'conditions'?: Array<IoK8sApimachineryPkgApisMetaV1Condition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApimachineryPkgApisMetaV1Condition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiNetworkingV1NetworkPolicyStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

