/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery } from './IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery.ts';
import { IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR } from './IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR.ts';
import { HttpFile } from '../http/http.ts';

/**
* APIGroup contains the name, the supported versions, and the preferred version of a group.
*/
export class IoK8sApimachineryPkgApisMetaV1APIGroup {
    /**
    * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    */
    'apiVersion'?: string;
    /**
    * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    */
    'kind'?: string;
    /**
    * name is the name of the group.
    */
    'name': string;
    'preferredVersion'?: IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery;
    /**
    * a map of client CIDR to server address that is serving this group. This is to help clients reach servers in the most network-efficient way possible. Clients can use the appropriate server address as per the CIDR that they match. In case of multiple matches, clients should use the longest matching CIDR. The server returns only those CIDRs that it thinks that the client can match. For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP. Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
    */
    'serverAddressByClientCIDRs'?: Array<IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR>;
    /**
    * versions are the versions supported in this group.
    */
    'versions': Array<IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "preferredVersion",
            "baseName": "preferredVersion",
            "type": "IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery",
            "format": ""
        },
        {
            "name": "serverAddressByClientCIDRs",
            "baseName": "serverAddressByClientCIDRs",
            "type": "Array<IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR>",
            "format": ""
        },
        {
            "name": "versions",
            "baseName": "versions",
            "type": "Array<IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApimachineryPkgApisMetaV1APIGroup.attributeTypeMap;
    }

    public constructor() {
    }
}

