/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAutoscalingV2beta2CrossVersionObjectReference } from './IoK8sApiAutoscalingV2beta2CrossVersionObjectReference.ts';
import { IoK8sApiAutoscalingV2beta2MetricIdentifier } from './IoK8sApiAutoscalingV2beta2MetricIdentifier.ts';
import { IoK8sApiAutoscalingV2beta2MetricValueStatus } from './IoK8sApiAutoscalingV2beta2MetricValueStatus.ts';
import { HttpFile } from '../http/http.ts';

/**
* ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
*/
export class IoK8sApiAutoscalingV2beta2ObjectMetricStatus {
    'current': IoK8sApiAutoscalingV2beta2MetricValueStatus;
    'describedObject': IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
    'metric': IoK8sApiAutoscalingV2beta2MetricIdentifier;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "current",
            "baseName": "current",
            "type": "IoK8sApiAutoscalingV2beta2MetricValueStatus",
            "format": ""
        },
        {
            "name": "describedObject",
            "baseName": "describedObject",
            "type": "IoK8sApiAutoscalingV2beta2CrossVersionObjectReference",
            "format": ""
        },
        {
            "name": "metric",
            "baseName": "metric",
            "type": "IoK8sApiAutoscalingV2beta2MetricIdentifier",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAutoscalingV2beta2ObjectMetricStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

