/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1ObjectReference } from './IoK8sApiCoreV1ObjectReference.ts';
import { HttpFile } from '../http/http.ts';

/**
* CronJobStatus represents the current state of a cron job.
*/
export class IoK8sApiBatchV1CronJobStatus {
    /**
    * A list of pointers to currently running jobs.
    */
    'active'?: Array<IoK8sApiCoreV1ObjectReference>;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'lastScheduleTime'?: Date;
    /**
    * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
    */
    'lastSuccessfulTime'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "Array<IoK8sApiCoreV1ObjectReference>",
            "format": ""
        },
        {
            "name": "lastScheduleTime",
            "baseName": "lastScheduleTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastSuccessfulTime",
            "baseName": "lastSuccessfulTime",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiBatchV1CronJobStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

