/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiFlowcontrolV1beta2GroupSubject } from './IoK8sApiFlowcontrolV1beta2GroupSubject.ts';
import { IoK8sApiFlowcontrolV1beta2ServiceAccountSubject } from './IoK8sApiFlowcontrolV1beta2ServiceAccountSubject.ts';
import { IoK8sApiFlowcontrolV1beta2UserSubject } from './IoK8sApiFlowcontrolV1beta2UserSubject.ts';
import { HttpFile } from '../http/http.ts';

/**
* Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
*/
export class IoK8sApiFlowcontrolV1beta2Subject {
    'group'?: IoK8sApiFlowcontrolV1beta2GroupSubject;
    /**
    * `kind` indicates which one of the other fields is non-empty. Required
    */
    'kind': string;
    'serviceAccount'?: IoK8sApiFlowcontrolV1beta2ServiceAccountSubject;
    'user'?: IoK8sApiFlowcontrolV1beta2UserSubject;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "IoK8sApiFlowcontrolV1beta2GroupSubject",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceAccount",
            "baseName": "serviceAccount",
            "type": "IoK8sApiFlowcontrolV1beta2ServiceAccountSubject",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "IoK8sApiFlowcontrolV1beta2UserSubject",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiFlowcontrolV1beta2Subject.attributeTypeMap;
    }

    public constructor() {
    }
}

