/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1AttachedVolume } from './IoK8sApiCoreV1AttachedVolume.ts';
import { IoK8sApiCoreV1ContainerImage } from './IoK8sApiCoreV1ContainerImage.ts';
import { IoK8sApiCoreV1NodeAddress } from './IoK8sApiCoreV1NodeAddress.ts';
import { IoK8sApiCoreV1NodeCondition } from './IoK8sApiCoreV1NodeCondition.ts';
import { IoK8sApiCoreV1NodeConfigStatus } from './IoK8sApiCoreV1NodeConfigStatus.ts';
import { IoK8sApiCoreV1NodeDaemonEndpoints } from './IoK8sApiCoreV1NodeDaemonEndpoints.ts';
import { IoK8sApiCoreV1NodeSystemInfo } from './IoK8sApiCoreV1NodeSystemInfo.ts';
import { HttpFile } from '../http/http.ts';

/**
* NodeStatus is information about the current status of a node.
*/
export class IoK8sApiCoreV1NodeStatus {
    /**
    * List of addresses reachable to the node. Queried from cloud provider, if available. More info: https://kubernetes.io/docs/concepts/nodes/node/#addresses Note: This field is declared as mergeable, but the merge key is not sufficiently unique, which can cause data corruption when it is merged. Callers should instead use a full-replacement patch. See http://pr.k8s.io/79391 for an example.
    */
    'addresses'?: Array<IoK8sApiCoreV1NodeAddress>;
    /**
    * Allocatable represents the resources of a node that are available for scheduling. Defaults to Capacity.
    */
    'allocatable'?: { [key: string]: string; };
    /**
    * Capacity represents the total resources of a node. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#capacity
    */
    'capacity'?: { [key: string]: string; };
    /**
    * Conditions is an array of current observed node conditions. More info: https://kubernetes.io/docs/concepts/nodes/node/#condition
    */
    'conditions'?: Array<IoK8sApiCoreV1NodeCondition>;
    'config'?: IoK8sApiCoreV1NodeConfigStatus;
    'daemonEndpoints'?: IoK8sApiCoreV1NodeDaemonEndpoints;
    /**
    * List of container images on this node
    */
    'images'?: Array<IoK8sApiCoreV1ContainerImage>;
    'nodeInfo'?: IoK8sApiCoreV1NodeSystemInfo;
    /**
    * NodePhase is the recently observed lifecycle phase of the node. More info: https://kubernetes.io/docs/concepts/nodes/node/#phase The field is never populated, and now is deprecated.  Possible enum values:  - `\"Pending\"` means the node has been created/added by the system, but not configured.  - `\"Running\"` means the node has been configured and has Kubernetes components running.  - `\"Terminated\"` means the node has been removed from the cluster.
    */
    'phase'?: IoK8sApiCoreV1NodeStatusPhaseEnum;
    /**
    * List of volumes that are attached to the node.
    */
    'volumesAttached'?: Array<IoK8sApiCoreV1AttachedVolume>;
    /**
    * List of attachable volumes in use (mounted) by the node.
    */
    'volumesInUse'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addresses",
            "baseName": "addresses",
            "type": "Array<IoK8sApiCoreV1NodeAddress>",
            "format": ""
        },
        {
            "name": "allocatable",
            "baseName": "allocatable",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiCoreV1NodeCondition>",
            "format": ""
        },
        {
            "name": "config",
            "baseName": "config",
            "type": "IoK8sApiCoreV1NodeConfigStatus",
            "format": ""
        },
        {
            "name": "daemonEndpoints",
            "baseName": "daemonEndpoints",
            "type": "IoK8sApiCoreV1NodeDaemonEndpoints",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<IoK8sApiCoreV1ContainerImage>",
            "format": ""
        },
        {
            "name": "nodeInfo",
            "baseName": "nodeInfo",
            "type": "IoK8sApiCoreV1NodeSystemInfo",
            "format": ""
        },
        {
            "name": "phase",
            "baseName": "phase",
            "type": "IoK8sApiCoreV1NodeStatusPhaseEnum",
            "format": ""
        },
        {
            "name": "volumesAttached",
            "baseName": "volumesAttached",
            "type": "Array<IoK8sApiCoreV1AttachedVolume>",
            "format": ""
        },
        {
            "name": "volumesInUse",
            "baseName": "volumesInUse",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1NodeStatus.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IoK8sApiCoreV1NodeStatusPhaseEnum = "Pending" | "Running" | "Terminated" ;

