/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1NamespaceCondition } from './IoK8sApiCoreV1NamespaceCondition.ts';
import { HttpFile } from '../http/http.ts';

/**
* NamespaceStatus is information about the current status of a Namespace.
*/
export class IoK8sApiCoreV1NamespaceStatus {
    /**
    * Represents the latest available observations of a namespace's current state.
    */
    'conditions'?: Array<IoK8sApiCoreV1NamespaceCondition>;
    /**
    * Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/  Possible enum values:  - `\"Active\"` means the namespace is available for use in the system  - `\"Terminating\"` means the namespace is undergoing graceful termination
    */
    'phase'?: IoK8sApiCoreV1NamespaceStatusPhaseEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiCoreV1NamespaceCondition>",
            "format": ""
        },
        {
            "name": "phase",
            "baseName": "phase",
            "type": "IoK8sApiCoreV1NamespaceStatusPhaseEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1NamespaceStatus.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IoK8sApiCoreV1NamespaceStatusPhaseEnum = "Active" | "Terminating" ;

