/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiFlowcontrolV1beta2FlowDistinguisherMethod } from './IoK8sApiFlowcontrolV1beta2FlowDistinguisherMethod.ts';
import { IoK8sApiFlowcontrolV1beta2PolicyRulesWithSubjects } from './IoK8sApiFlowcontrolV1beta2PolicyRulesWithSubjects.ts';
import { IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationReference } from './IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationReference.ts';
import { HttpFile } from '../http/http.ts';

/**
* FlowSchemaSpec describes how the FlowSchema's specification looks like.
*/
export class IoK8sApiFlowcontrolV1beta2FlowSchemaSpec {
    'distinguisherMethod'?: IoK8sApiFlowcontrolV1beta2FlowDistinguisherMethod;
    /**
    * `matchingPrecedence` is used to choose among the FlowSchemas that match a given request. The chosen FlowSchema is among those with the numerically lowest (which we take to be logically highest) MatchingPrecedence.  Each MatchingPrecedence value must be ranged in [1,10000]. Note that if the precedence is not specified, it will be set to 1000 as default.
    */
    'matchingPrecedence'?: number;
    'priorityLevelConfiguration': IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationReference;
    /**
    * `rules` describes which requests will match this flow schema. This FlowSchema matches a request if and only if at least one member of rules matches the request. if it is an empty slice, there will be no requests matching the FlowSchema.
    */
    'rules'?: Array<IoK8sApiFlowcontrolV1beta2PolicyRulesWithSubjects>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "distinguisherMethod",
            "baseName": "distinguisherMethod",
            "type": "IoK8sApiFlowcontrolV1beta2FlowDistinguisherMethod",
            "format": ""
        },
        {
            "name": "matchingPrecedence",
            "baseName": "matchingPrecedence",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "priorityLevelConfiguration",
            "baseName": "priorityLevelConfiguration",
            "type": "IoK8sApiFlowcontrolV1beta2PriorityLevelConfigurationReference",
            "format": ""
        },
        {
            "name": "rules",
            "baseName": "rules",
            "type": "Array<IoK8sApiFlowcontrolV1beta2PolicyRulesWithSubjects>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiFlowcontrolV1beta2FlowSchemaSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

