/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiAppsV1RollingUpdateDaemonSet } from './IoK8sApiAppsV1RollingUpdateDaemonSet.ts';
import { HttpFile } from '../http/http.ts';

/**
* DaemonSetUpdateStrategy is a struct used to control the update strategy for a DaemonSet.
*/
export class IoK8sApiAppsV1DaemonSetUpdateStrategy {
    'rollingUpdate'?: IoK8sApiAppsV1RollingUpdateDaemonSet;
    /**
    * Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is RollingUpdate.  Possible enum values:  - `\"OnDelete\"` Replace the old daemons only when it's killed  - `\"RollingUpdate\"` Replace the old daemons by new ones using rolling update i.e replace them on each node one after the other.
    */
    'type'?: IoK8sApiAppsV1DaemonSetUpdateStrategyTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rollingUpdate",
            "baseName": "rollingUpdate",
            "type": "IoK8sApiAppsV1RollingUpdateDaemonSet",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "IoK8sApiAppsV1DaemonSetUpdateStrategyTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiAppsV1DaemonSetUpdateStrategy.attributeTypeMap;
    }

    public constructor() {
    }
}


export type IoK8sApiAppsV1DaemonSetUpdateStrategyTypeEnum = "OnDelete" | "RollingUpdate" ;

