/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1NodeAffinity } from './IoK8sApiCoreV1NodeAffinity.ts';
import { IoK8sApiCoreV1PodAffinity } from './IoK8sApiCoreV1PodAffinity.ts';
import { IoK8sApiCoreV1PodAntiAffinity } from './IoK8sApiCoreV1PodAntiAffinity.ts';
import { HttpFile } from '../http/http.ts';

/**
* Affinity is a group of affinity scheduling rules.
*/
export class IoK8sApiCoreV1Affinity {
    'nodeAffinity'?: IoK8sApiCoreV1NodeAffinity;
    'podAffinity'?: IoK8sApiCoreV1PodAffinity;
    'podAntiAffinity'?: IoK8sApiCoreV1PodAntiAffinity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nodeAffinity",
            "baseName": "nodeAffinity",
            "type": "IoK8sApiCoreV1NodeAffinity",
            "format": ""
        },
        {
            "name": "podAffinity",
            "baseName": "podAffinity",
            "type": "IoK8sApiCoreV1PodAffinity",
            "format": ""
        },
        {
            "name": "podAntiAffinity",
            "baseName": "podAntiAffinity",
            "type": "IoK8sApiCoreV1PodAntiAffinity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1Affinity.attributeTypeMap;
    }

    public constructor() {
    }
}

