/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiDiscoveryV1ForZone } from './IoK8sApiDiscoveryV1ForZone.ts';
import { HttpFile } from '../http/http.ts';

/**
* EndpointHints provides hints describing how an endpoint should be consumed.
*/
export class IoK8sApiDiscoveryV1EndpointHints {
    /**
    * forZones indicates the zone(s) this endpoint should be consumed by to enable topology aware routing.
    */
    'forZones'?: Array<IoK8sApiDiscoveryV1ForZone>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "forZones",
            "baseName": "forZones",
            "type": "Array<IoK8sApiDiscoveryV1ForZone>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiDiscoveryV1EndpointHints.attributeTypeMap;
    }

    public constructor() {
    }
}

