/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1TopologySelectorLabelRequirement } from './IoK8sApiCoreV1TopologySelectorLabelRequirement.ts';
import { HttpFile } from '../http/http.ts';

/**
* A topology selector term represents the result of label queries. A null or empty topology selector term matches no objects. The requirements of them are ANDed. It provides a subset of functionality as NodeSelectorTerm. This is an alpha feature and may change in the future.
*/
export class IoK8sApiCoreV1TopologySelectorTerm {
    /**
    * A list of topology selector requirements by labels.
    */
    'matchLabelExpressions'?: Array<IoK8sApiCoreV1TopologySelectorLabelRequirement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "matchLabelExpressions",
            "baseName": "matchLabelExpressions",
            "type": "Array<IoK8sApiCoreV1TopologySelectorLabelRequirement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCoreV1TopologySelectorTerm.attributeTypeMap;
    }

    public constructor() {
    }
}

