syntax match K8sListHeader /\%1l.*/
syntax match K8sPodsFailed /.*Failed.*/
syntax match K8sPodsFailed /.*RunContainerError.*/
syntax match K8sPodsFailed /.*CrashLoopBackOff.*/
syntax match K8sPodsFailed /.*ErrImagePull.*/
syntax match K8sPodsFailed /.*ImagePullBackOff.*/
syntax match K8sPodsFailed /.*Error.*/
syntax match K8sPodsFailed /.*OOMKilled.*/
syntax match K8sPodsUp /.*Running.*/
syntax match K8sPodsTerminating /.*Terminating.*/
syntax match K8sPodsCreating /.*ContainerCreating.*/
