name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'doc/k8s.txt'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/k8s.txt'
jobs:
  lint:
    strategy:
      matrix:
        deno-version: [v1.x]
        os: [ubuntu-latest]
    name: deno lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: run lint
        run: deno lint --ignore=denops/k8s/models
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
        host_version:
          - vim: "v8.2.3452"
            nvim: "v0.6.0"
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "${{ matrix.version }}"
      - uses: thinca/action-setup-vim@v1
        id: vim
        with:
          vim_type: "Vim"
          vim_version: "${{ matrix.host_version.vim }}"
          download: "never"
      - name: Check Vim
        run: |
          echo ${DENOPS_TEST_VIM}
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable_path }}
      - uses: thinca/action-setup-vim@v1
        id: nvim
        with:
          vim_type: "Neovim"
          vim_version: "${{ matrix.host_version.nvim }}"
      - name: Check Neovim
        run: |
          echo ${DENOPS_TEST_NVIM}
        env:
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable_path }}
      - name: Clone denops
        id: denops
        run: |
          git clone https://github.com/vim-denops/denops.vim $HOME/denops.vim
          echo "::set-output name=path::$HOME/denops.vim"
      - name: Setup themis
        id: themis
        run: |
          git clone https://github.com/thinca/vim-themis $HOME/vim-themis
          echo "::set-output name=path::$HOME/vim-themis"
          echo "$HOME/vim-themis/bin" >> $GITHUB_PATH
      - name: Test
        run: |
          make test
          make test-e2e
        env:
          DENOPS_TEST_VIM: ${{ steps.vim.outputs.executable_path }}
          DENOPS_TEST_NVIM: ${{ steps.nvim.outputs.executable_path }}
          DENOPS_PATH: ${{ steps.denops.outputs.path }}
        timeout-minutes: 5
